
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'comienza este norte oeste sursec : sec instr \n           | comienza instr : esteinstr : norteinstr : oesteinstr : sur'
    
_lr_action_items = {'comienza':([0,],[2,]),'$end':([1,2,3,4,5,6,7,],[0,-2,-1,-3,-4,-5,-6,]),'este':([1,2,3,4,5,6,7,],[4,-2,-1,-3,-4,-5,-6,]),'norte':([1,2,3,4,5,6,7,],[5,-2,-1,-3,-4,-5,-6,]),'oeste':([1,2,3,4,5,6,7,],[6,-2,-1,-3,-4,-5,-6,]),'sur':([1,2,3,4,5,6,7,],[7,-2,-1,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sec':([0,],[1,]),'instr':([1,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sec","S'",1,None,None,None),
  ('sec -> sec instr','sec',2,'p_sec','robot.py',30),
  ('sec -> comienza','sec',1,'p_sec','robot.py',31),
  ('instr -> este','instr',1,'p_instr_este','robot.py',35),
  ('instr -> norte','instr',1,'p_instr_norte','robot.py',39),
  ('instr -> oeste','instr',1,'p_instr_oeste','robot.py',43),
  ('instr -> sur','instr',1,'p_instr_sur','robot.py',47),
]
